package com.govos.cmp.mapper;

import com.govos.cmp.dto.ComplaintCreateRequest;
import com.govos.cmp.dto.ComplaintDto;
import com.govos.cmp.dto.ComplaintUpdateRequest;
import com.govos.cmp.entity.Complaint;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface ComplaintMapper {

    @Mapping(source = "location.stateKey", target = "stateKey")
    @Mapping(source = "location.districtKey", target = "districtKey")
    @Mapping(source = "location.ulbKey", target = "ulbKey")
    @Mapping(source = "location.wardKey", target = "wardKey")
    @Mapping(source = "location.villageKey", target = "villageKey")
    @Mapping(source = "location.latitude", target = "latitude")
    @Mapping(source = "location.longitude", target = "longitude")
    @Mapping(source = "location.address", target = "address")
    @Mapping(source = "location.landmark", target = "landmark")
    @Mapping(source = "location.pincode", target = "pincode")
    @Mapping(source = "location.geoJson", target = "geoJson")
    ComplaintDto toDto(Complaint entity);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "code", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "updatedDate", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "workflowInstanceId", ignore = true)
    @Mapping(target = "assignedOfficerId", ignore = true)
    @Mapping(target = "resolvedByUserId", ignore = true)
    @Mapping(target = "closedByUserId", ignore = true)
    @Mapping(target = "submittedAt", ignore = true)
    @Mapping(target = "closedAt", ignore = true)
    @Mapping(target = "archivedAt", ignore = true)
    @Mapping(target = "rejectionReasonKey", ignore = true)
    @Mapping(target = "closureReasonKey", ignore = true)
    @Mapping(target = "isDuplicate", ignore = true)
    @Mapping(target = "primaryComplaintId", ignore = true)
    @Mapping(target = "mergedIntoComplaintId", ignore = true)
    @Mapping(target = "assignments", ignore = true)
    @Mapping(target = "comments", ignore = true)
    @Mapping(target = "attachments", ignore = true)
    @Mapping(target = "statusHistory", ignore = true)
    @Mapping(target = "escalations", ignore = true)
    @Mapping(target = "duplicates", ignore = true)
    @Mapping(target = "merges", ignore = true)
    @Mapping(target = "feedback", ignore = true)
    @Mapping(target = "location.stateKey", source = "stateKey")
    @Mapping(target = "location.districtKey", source = "districtKey")
    @Mapping(target = "location.ulbKey", source = "ulbKey")
    @Mapping(target = "location.wardKey", source = "wardKey")
    @Mapping(target = "location.villageKey", source = "villageKey")
    @Mapping(target = "location.latitude", source = "latitude")
    @Mapping(target = "location.longitude", source = "longitude")
    @Mapping(target = "location.address", source = "address")
    @Mapping(target = "location.landmark", source = "landmark")
    @Mapping(target = "location.pincode", source = "pincode")
    @Mapping(target = "location.geoJson", source = "geoJson")
    Complaint toEntity(ComplaintCreateRequest request);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "code", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "updatedDate", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "source", ignore = true)
    @Mapping(target = "citizenUserId", ignore = true)
    @Mapping(target = "submittedByUserId", ignore = true)
    @Mapping(target = "organizationId", ignore = true)
    @Mapping(target = "workflowInstanceId", ignore = true)
    @Mapping(target = "assignedOfficerId", ignore = true)
    @Mapping(target = "resolvedByUserId", ignore = true)
    @Mapping(target = "closedByUserId", ignore = true)
    @Mapping(target = "submittedAt", ignore = true)
    @Mapping(target = "closedAt", ignore = true)
    @Mapping(target = "archivedAt", ignore = true)
    @Mapping(target = "rejectionReasonKey", ignore = true)
    @Mapping(target = "closureReasonKey", ignore = true)
    @Mapping(target = "isDuplicate", ignore = true)
    @Mapping(target = "primaryComplaintId", ignore = true)
    @Mapping(target = "mergedIntoComplaintId", ignore = true)
    @Mapping(target = "assignments", ignore = true)
    @Mapping(target = "comments", ignore = true)
    @Mapping(target = "attachments", ignore = true)
    @Mapping(target = "statusHistory", ignore = true)
    @Mapping(target = "escalations", ignore = true)
    @Mapping(target = "duplicates", ignore = true)
    @Mapping(target = "merges", ignore = true)
    @Mapping(target = "feedback", ignore = true)
    @Mapping(target = "location.stateKey", source = "stateKey")
    @Mapping(target = "location.districtKey", source = "districtKey")
    @Mapping(target = "location.ulbKey", source = "ulbKey")
    @Mapping(target = "location.wardKey", source = "wardKey")
    @Mapping(target = "location.villageKey", source = "villageKey")
    @Mapping(target = "location.latitude", source = "latitude")
    @Mapping(target = "location.longitude", source = "longitude")
    @Mapping(target = "location.address", source = "address")
    @Mapping(target = "location.landmark", source = "landmark")
    @Mapping(target = "location.pincode", source = "pincode")
    @Mapping(target = "location.geoJson", source = "geoJson")
    void updateEntity(ComplaintUpdateRequest request, @MappingTarget Complaint entity);
}
