package com.govos.srh.observability;

public enum SearchObservationEventType {
    SEARCH_STARTED,
    SEARCH_COMPLETED,
    SEARCH_FAILED,
    SEMANTIC_SEARCH_STARTED,
    SEMANTIC_SEARCH_COMPLETED,
    BULK_INDEX_STARTED,
    BULK_INDEX_COMPLETED,
    SCHEDULER_STARTED,
    SCHEDULER_COMPLETED,
    CLUSTER_HEALTH_CHECKED
}
