spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO
    com.govos: DEBUG
    org.springframework.web: INFO

management:
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
