spring:
  application:
    name: govos-api
  profiles:
    active: local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 0.1.0-SNAPSHOT
    description: GovOS Platform API

govos:
  api:
    version: v1
    base-path: /api/v1
  security:
    jwt:
      secret: ${GOVOS_JWT_SECRET:govos-local-jwt-secret-key-minimum-sixty-four-bytes-long-for-hs512-signing!!}
      issuer: govos
      access-token-ttl: 15m
      refresh-token-ttl: 7d
      clock-skew: 60s
    session:
      max-per-user: 5
    lockout:
      max-attempts: 5

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
